### ISSUE TITLE
status for GitHub action stopped working

### ISSUE THREAD

**Issue by paulz** [ospfranco/cidemon_issues#1]
seeing blank screen and no status even we had it working with GitHub token.

<img width="876" alt="image" src="https://user-images.githubusercontent.com/59230/116945724-3f462700-ac2d-11eb-983d-cc8926ca3bc6.png">

<img width="879" alt="image" src="https://user-images.githubusercontent.com/59230/116945791-5ab13200-ac2d-11eb-9035-1c2a1d4c3033.png">

**Comment by ospfranco** [comment]
You have to enable either: "Fetch pull requests" and/or "Fetch branches", it was just a small change to have more control over what gets displayed.

**Comment by ospfranco** [comment]
<img width="1026" alt="Screen Shot 2021-05-04 at 3 47 49 PM" src="https://user-images.githubusercontent.com/1634213/117013363-15096d80-acf0-11eb-8eee-b60cbf123729.png">

Just trying stuff on my machine and even with just a github token everything seems to be working @paulz, can you tell me which version are you running?

**Comment by paulz** [comment]
Thank you, finally got it working:
<img width="900" alt="image" src="https://user-images.githubusercontent.com/59230/118192074-70c3ad00-b3fa-11eb-9cab-e7eb9e512ef4.png">

Couple of ideas for future:
1. link directly here from the app (we had to click on your GitHub profile first)
2. make it easier to configure for GitHub Actions, (I like to see Save button personally)
3. make 3 balls icon one large ball of different colors when I have 1 repo

**Comment by ospfranco** [comment]
1. sure, valid complain :)
2. Yeah, everything is auto-saved, changing it to use save buttons is kinda a large refactor... how about a saved pop-up or something like that?
3. I know some of the users of CCMenu like to have a single status indicator, but that can be deceiving... but maybe I can put a setting on the menu for it
