### ISSUE TITLE
Enable workflow selection for GitHub Actions 

### ISSUE THREAD

**Issue by paulz** [ospfranco/cidemon_issues#2]
**Is your feature request related to a problem? Please describe.**
We have multiple scheduled workflows for nightly runs and want to see their status.

**Describe the solution you'd like**
Enable selection of workflows to monitor 

**Describe alternatives you've considered**
Open GitHub in browser. Use badge

**Additional context**
<img width="773" alt="image" src="https://user-images.githubusercontent.com/59230/118192902-bb91f480-b3fb-11eb-9d1c-a11a6817fa35.png">
here is our list of workflows. We need to monitor 2 of them

**Comment by paulz** [comment]
currently we are only able to select branches or PRs to monitor.
<img width="684" alt="image" src="https://user-images.githubusercontent.com/59230/118193028-f3993780-b3fb-11eb-9d14-8b968cacf246.png">

**Comment by ospfranco** [comment]
I need to take a look, to see if the API returns the necessary that, if so, totally doable

**Comment by ospfranco** [comment]
Ok, a bunch of new features have been added:

- It's now possible to pull GitHub workflows
- You can now select a single icon for the status bar
- Whenever there is a change in the GitHub configuration there is now visual feedback
- Also the link to report issues via GitHub has also been improved to go directly to the issues page

The app has been sent for review, so hopefully you will be able to see the changes today. Thanks a lot for the feedback!

**Comment by ospfranco** [comment]
App is approved, check for the update, let me know if everything is working, if so, I'll close this issue

**Comment by paulz** [comment]
New version looks great! Thank you.

**Comment by ospfranco** [comment]
cheers!
